{{- if .Values.rbac.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: winm-server
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "winm.labels" . | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: winm-consumer
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "winm.labels" . | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: winm-llm
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "winm.labels" . | nindent 4 }}
{{- end }}
